"""
validation_engine.py
=======================

Core validation engine for schema-based normalization, cross-sheet rule
evaluation, dataset reconciliation, and optional SQL-backed audit logging.

This module defines the `ValidationEngine` class, which orchestrates
end-to-end validation of multi-sheet workbooks submitted by external
organizations (e.g., CareerConneCT, Good Jobs Challenge).

Overview
--------
The engine performs the following high-level steps:

1. **Sheet-level normalization**
   • Applies column-type validator classes (e.g., `categoricalColumn`,
     `dateTimeColumn`, `identifierColumn`) to coerce raw spreadsheet values
     into consistent formats.
   • Produces both raw and normalized versions of each column.
   • Generates column-level validation errors.

2. **Identity construction**
   • Establishes an `id_key` per record:
       - simple format: constructed from name fields
       - multi-sheet format: expected from identity sheet
   • Used as the primary key for cross-sheet alignment.

3. **Duplicate and mismatch handling**
   • Detects duplicate `id_key` values within sheets.
   • Removes duplicated keys globally prior to merging.
   • Identifies cross-sheet inconsistencies:
       - missing_in_sheet
       - extra_in_sheet
       - duplicate_in_sheet

4. **Cross-sheet merging**
   • Inner-joins all sheets on `id_key`.
   • Retains only participants present in all sheets.
   • Encodes sheet provenance in column names using the delimiter `_|_|_`.

5. **Cross-sheet rule evaluation**
   • Delegates rule execution to `CrossRuleEngine`.
   • Rules operate on the merged dataset (`single_sheet`), not individual sheets.

6. **Error aggregation**
   • Combines normalization errors and cross-sheet rule violations.
   • Accessible via `engine.errors` or `engine.get_all_errors()`.

7. **Optional database logging**
   When `logging=True`, the engine:
   • creates validation runs (`run_id`)
   • resolves `person_id` and `participant_id`
   • logs normalized values and presence tracking
   • persists validation violations and mismatch events

Inputs
------
The engine requires:
    - ``workbook_definitions`` (dict):
        Schema describing sheets, expected columns, column types,
        and accepted responses.

    - ``cross_rules`` (list[tuple], optional):
        Rule sets applied during cross-sheet validation, structured as:
        [(label, ruleset), ...]

    - ``logging`` (bool):
        Enables write-back to the SQL logging database via
        ``ValidationDBLogger``.

Within `validate_workbook`, the caller must supply:
    - ``file`` (str):
        Identifier in the form ``org|period`` or
        ``org|period|filename``. Only the first two segments are used.

    - ``workbook_type`` (str):
        Dataset name (e.g., "training data").

    - ``workbook_format`` (str):
        Workbook layout ("simple format" or "four sheet format").

    - ``dfs_by_sheet`` (dict[str, pandas.DataFrame]):
        Raw data from each sheet after loading.

    - ``passed_identity_sheet`` (str):
        Required for multi-sheet formats. Ignored for simple format.

    - ``keycreators`` (list of (KeyCreator, str), optional):
        Used when logging is enabled to generate additional identity keys.

Outputs
-------
Attributes populated during validation:

    - ``normalized_data`` (dict[str → DataFrame]):
        Per-sheet normalized DataFrames (raw + normalized columns).

    - ``single_sheet`` (DataFrame):
        Fully merged dataset across sheets using `id_key`.

    - ``returnable_data`` (DataFrame):
        Reduced dataset containing only normalized columns,
        with suffixes removed for downstream use.

    - ``errors`` (list[DataFrame]):
        Column-level and cross-sheet validation error frames.

    - ``column_error_index`` (dict[(sheet, column) → set[int]]):
        Tracks row indices associated with column-level errors.

    - ``mismatches`` (list[dict]):
        Records of cross-sheet key inconsistencies.

Methods:
    - ``validate_workbook``:
        Main entry point for executing the full validation workflow.

    - ``get_all_errors``:
        Returns a single concatenated DataFrame of all errors.

Assumptions and Constraints
---------------------------
- ``workbook_definitions`` fully describe all sheets and expected columns.
- Row tracking relies on sheet-specific columns (e.g., `row_number_{sheet}`),
  generated by the workbook loader.
- Identity resolution depends on workbook format:
    - simple format: inferred
    - multi-sheet format: explicitly provided
- Cross-sheet merging uses an inner join on `id_key`, which may drop records.
- Column provenance in merged outputs is encoded using `_|_|_`.

Side Effects
------------
- When ``logging=True``, this module writes:
    - run metadata
    - normalized cell values
    - person/participant resolution events
    - presence logs
    - mismatch records
    - validation rule violations
  to the SQL logging database via ``ValidationDBLogger``.

Security / PII Notes
--------------------
- This engine processes sensitive PII including names, DOB, ZIP code,
  and state ID values.
- Identity keys are generated using SHA-256, but raw PII exists in memory
  during normalization and logging.
- Database logs may contain raw and normalized values; appropriate access
  controls must be enforced externally.

Notes
-----
- Inner joins across sheets will remove participants not present in all sheets.
- Duplicate `id_key` values are removed before merging.
- Logging mode performs row-wise operations and may be slow for large datasets.

This module is intended to be imported by higher-level orchestration scripts
(e.g., `cc_validation_main.py`) and is not designed for direct command-line
execution.
"""

import pandas as pd
from validation_engine.validation_column_types import *
from validation_engine.cross_rule_engine import CrossRuleEngine

from validation_engine.column_names import (
    add_sheet_suffix,
    strip_normalized_suffixes,
    assert_sheet_provenance
)

### SQL Logging Related Imports 
from validation_engine.db_logger import ValidationDBLogger
from hashlib import sha256
from datetime import datetime
import warnings


### this mapping relates to the 'validation_column_types', classes designed to capture normalization 
### routines for different data types. 

COLUMN_CLASS_MAP = {
    "multiCategorical": multiCategoricalColumn,
    "categorical": categoricalColumn,
    "fileSpecificCategorical":fileSpecificCategoricalColumn,
    "identifier": identifierColumn,
    "boolean": booleanColumn,
    "dateTime": dateTimeColumn,
    "zipCode": zipCodeColumn,
    "stateID7": stateID7Column,
    "ONETCode": ONETCodeColumn,
    "CIPCode": CIPCodeColumn,
    "hourlyWage": hourlyWageColumn,
    "hoursWorked": hoursWorkedColumn,
    "NAICSCode": NAICSCodeColumn
}

class ValidationEngine:
    """
    Core orchestrator for sheet-level column validation in CareerConneCT /
    workforce-data workbooks.

    The engine applies:
       • column-type normalization (dates, categorical, integers, Booleans, ZIPs, etc.)
       • file-specific categorical validation (for org-dependent fields)
       • error generation with row-level metadata
       • row-dropping rules for entirely blank participant records
       • construction of `column_error_index` for downstream cross-sheet checks

    This class handles validation for **one workbook at a time**.  
    Multi-sheet and cross-sheet coordination occurs in the calling
    `validate_workbook()` method (not included in this snippet).

    Attributes:
        workbook_definitions (dict):
            Schema describing expected columns, column types, and accepted responses
            for each sheet in the workbook.
        cross_rules (dict):
            Optional override for cross-sheet validation rules.
        logging (bool):
            If True, downstream caller logs to SQLite via `ValidationDBLogger`.
        normalized_data (dict[str, DataFrame]):
            Resulting normalized sheets after validation.
        errors (list[DataFrame]):
            List of error DataFrames produced per sheet.
        column_error_index (dict[(sheet, column) → set[int]]):
            Fast lookup for cross-rule engine; identifies failed rows per column.
        file (str or None):
            Identifier used when generating error reports (“org|quarter|filename”).
    """
    
    def __init__(self, workbook_definitions, cross_rules=None, logging = False, log_description = None, mismatch_check = True, db_path = None):
        
        ## file meta data navigation 
        self.workbook_definitions = workbook_definitions
        self.workbook_type = None
        self.workbook_format = None
        self.workbook_definitions_location = None
        
        self.cross_rules = cross_rules or {}
        self.normalized_data = {}   # {sheet_name: DataFrame}
        self.errors = []            # list of DataFrames
        self._validated = False
        self._cross_checked = False
        self.file = None 
        self.logging = logging 
        self.log_description = log_description
        self.mismatch_check = mismatch_check
        self.mismatches = []
        self.single_sheet = []
        self.db_logger = None
        self.run_id = None
        self.returnable_data = None
        self.db_path = db_path

        if self.logging:

            if not self.log_description:

                raise ValueError("Engine call must include a log_description argument if Logging is True")

            self.db_logger = ValidationDBLogger(db_path)
            

    def _validate_sheet(self, df, sheet_name, accepted_responses, row_offset=1):
        
        """
        Validate and normalize all columns for a single sheet.

        This method applies column-type validator classes (defined in
        `COLUMN_CLASS_MAP`) to each column specified in `accepted_responses`.
        It produces a normalized DataFrame alongside a structured error DataFrame.

        Args:
            df (pd.DataFrame):
                Raw sheet data as loaded by the WorkbookLoader.
            sheet_name (str):
                Name of the sheet being validated. Used for column naming
                and error metadata.
            accepted_responses (dict):
                Column-level schema for this sheet, e.g.:

                    {
                        "Date Entered Training": {"type": "dateTime", "required": True},
                        "County": {
                            "type": "categorical",
                            "accepted_responses": ["Hartford", "New Haven", ...]
                        },
                        ...
                    }

            row_offset (int, optional):
                Excel row offset used when translating DataFrame indices
                back into user-visible spreadsheet row numbers.

        Returns:
            tuple:
                (normalized_df, errors_df)

                • normalized_df (pd.DataFrame):
                    DataFrame containing:
                        - original raw columns
                        - corresponding `{column}_normalized` columns
                        - `id_key` (if present in input)
                        - `row_number_{sheet_name}` (if present in input)
                        - `source_file` (if present)

                    Rows where all non-identity columns are null are removed.

                • errors_df (pd.DataFrame):
                    Structured validation errors with columns:
                        ["file", "sheet", f"row_number_{sheet_name}",
                        "column", "rule", "severity", "raw_value", "normalized"]

                    Empty if no errors are detected.

        Behavior:
            • Applies type-specific normalization and formatting using validator classes.
            • For each column `X`, produces:
                - `X` (raw values)
                - `X_normalized` (validated / formatted values)
            • Records validation errors via each validator’s `errors_df()` method.
            • Drops rows that are entirely null across all non-identity columns.
            • Builds `self.column_error_index` mapping (sheet, column) → failing row indices.

        Side Effects:
            • Mutates `self.column_error_index`.
            • Sets `self._validated = True`.
            • Prints a message for any expected column not found in the input DataFrame.

        Notes:
            • Validation is column-wise; errors in one column do not halt processing.
            • Validators may coerce values (e.g., trimming, case normalization, type casting).
            • Row removal is based on post-normalization null checks.
            • Error row references depend on `row_number_{sheet_name}`; if this column
            is missing, downstream row tracking may be inconsistent.
        """
        normalized_cols = {}
        all_errors = []

        if "id_key" in df.columns:
            normalized_cols["id_key"] = df["id_key"]

        if f"row_number_{sheet_name}" in df.columns:
            normalized_cols[f"row_number_{sheet_name}"] = df[f"row_number_{sheet_name}"]
            
        if "source_file" in df.columns:
            normalized_cols["source_file"] = df["source_file"]

        for col, spec in accepted_responses.items():
            if col not in df.columns:
                print(f"skip {col}")
                continue

            col_type = spec.get("type")
            if not col_type:
                continue

            ### categorical responses require extra information passed by workbook_definitions
            cls = COLUMN_CLASS_MAP[col_type]
            if col_type == "categorical":
                accepted = spec.get("accepted_responses", [])
                validator = cls(
                    accepted_responses=accepted,
                    required=spec.get("required", False),
                    row_numbers=df[f"row_number_{sheet_name}"]
                )

            elif col_type == "multiCategorical":
                accepted = spec.get("accepted_responses", [])
                validator = cls(
                    accepted_responses=accepted,
                    required=spec.get("required", False),
                    row_numbers=df[f"row_number_{sheet_name}"]
                )

            elif col_type == "fileSpecificCategorical":
                accepted = spec.get("accepted_responses", [])
                validator = cls(
                    accepted_responses=accepted,
                    required=spec.get("required", False),
                    file=self.file.split("|")[0],
                    row_numbers=df[f"row_number_{sheet_name}"]
                )

            elif col_type == "hourlyWage":
                max_wage = spec.get("max_wage", 45)
                min_wage = spec.get("min_wage", 0)
                validator = cls(
                    max_wage=max_wage,
                    min_wage=min_wage,
                    required=spec.get("required", False),
                    row_numbers=df[f"row_number_{sheet_name}"]
                )

            else:
                validator = cls(
                    required=spec.get("required", False),
                    row_numbers=df[f"row_number_{sheet_name}"]
                )

            raw = df[col]
            s_norm = validator.normalize(raw)
            s_fmt = validator.format(s_norm)

            errs = validator.errors_df(col, raw, s_norm, file=self.file, sheet=sheet_name, row_offset=row_offset)    

            if not errs.empty:

                if "id_key" in df.columns:
                    errs["severity"] = "Normalization" # label violation as Normalization error
                    errs["id_key"] = df.loc[errs.index, "id_key"].values
            
                all_errors.append(errs)

            normalized_cols[col] = raw
            normalized_cols[f"{col}_normalized"] = s_fmt

            # --- MultiCategorical: add indicator columns ---
            if col_type == "multiCategorical":
                s_ohe = validator.indicators(s_fmt)
                num_indicators = s_ohe.shape[1]
                num_accepted_values = len(validator.canonicals)

                # sanity check (same as version 1)
                if num_indicators != num_accepted_values:
                    warnings.warn(
                        f"Number of indicator columns ({num_indicators}) does not match "
                        f"number of accepted values ({num_accepted_values}) for column "
                        f"'{col}' in sheet '{sheet_name}'."
                    )

                # add each OHE column
                for i, ohe_col in enumerate(s_ohe.columns):
                    normalized_cols[f"{ohe_col}"] = s_ohe.iloc[:, i]

        normalized_df = pd.DataFrame(normalized_cols, index=df.index)

        errors_df = pd.concat(all_errors) if all_errors else pd.DataFrame(
            columns=["file","sheet",f"row_number_{sheet_name}","column","rule", "severity", "raw_value","normalized"]
        )

        #         ### Moved this to the column type classes, inappropriate for the engine to be normalizing, leaving here for reference in case changes broke stuff 
        # normalized_df = normalized_df.replace(r"^\s*$", pd.NA, regex=True)    # empty or whitespace-only
        # normalized_df = normalized_df.replace(r"^0+$", pd.NA, regex=True)     # "0", "00", etc.
        # normalized_df = normalized_df.replace(
        #     to_replace=[
        #         "#VALUE!", "#REF!", "#DIV/0!", "#NAME?", "#NULL!", "#NUM!",
        #         "#N/A", "nan", "<NA>", "NaN"
        #     ],
        #     value=pd.NA
        # )

        # Drop rows that are all blank except id_key/row_number
        cols_to_check = [c for c in normalized_df.columns if c not in ["id_key", f"row_number_{sheet_name}"]]
        drop_mask = normalized_df[cols_to_check].isna().all(axis=1)
        dropped_row_numbers = normalized_df.loc[drop_mask, f"row_number_{sheet_name}"].tolist()
        normalized_df = normalized_df.loc[~drop_mask].copy()
        # ✅ Reindex to keep positional alignment with masks
        normalized_df.reset_index(drop=True, inplace=True)

        # Build column_error_index from the combined errors_df
        self.column_error_index = getattr(self, "column_error_index", {})
        if not errors_df.empty:
            for col in errors_df["column"].unique():
                bad_idx = errors_df.loc[errors_df["column"] == col].index
                if len(bad_idx):
                    self.column_error_index[(sheet_name, col)] = set(bad_idx)

        # --- Remove any errors that belong to fully blank rows ---
        if dropped_row_numbers:
            errors_df = errors_df[~errors_df["row_number"].isin(dropped_row_numbers)]

        self._validated = True

        return normalized_df, errors_df

    ## main function, the one implementing the other functions 
    def validate_workbook(self, file, workbook_type, workbook_format, dfs_by_sheet, passed_identity_sheet, keycreators = None):
        """
        Validate an entire workbook, normalize sheet data, reconcile participant
        identity across sheets, construct merged outputs, apply cross-sheet rules,
        and optionally persist results to a validation database.

        This method orchestrates the full validation pipeline:

        1. **Sheet-level validation**
        • Each sheet in `dfs_by_sheet` is processed via `_validate_sheet`.
        • Produces:
            - normalized per-sheet DataFrames (`self.normalized_data`)
            - column-level validation errors (`self.errors`)
        • Rows that are entirely null across non-identity columns are removed.

        2. **Identity construction**
        • Establishes an `id_key` per row:
            - simple format: constructed from `"First Name" | "Last Name"`
            - multi-sheet format: expected to already exist in the identity sheet
        • Determines identity sheet:
            - simple format: inferred from processed sheets (caller must ensure correctness)
            - four-sheet format: provided via `passed_identity_sheet`

        3. **Duplicate and mismatch handling**
        • Detects duplicate `id_key` values within sheets.
        • Removes all duplicated keys globally before merging.
        • Records mismatch events:
            - `"duplicate_in_sheet"`
            - `"missing_in_sheet"`
            - `"extra_in_sheet"`
        • Mismatches are stored in `self.mismatches` and optionally logged.

        4. **Cross-sheet merging**
        • All sheets are inner-joined on `id_key`.
        • Only participants present in *all* sheets are retained.
        • Column names are suffixed with `_|_|_{sheet_name}` to preserve provenance.
        • Result stored as:
            - `self.single_sheet` (fully merged dataset)

        5. **Returnable dataset construction**
        • A reduced dataset (`self.returnable_data`) is created:
            - includes only normalized columns
            - removes `_normalized` suffix
            - excludes raw columns
            - retains only rows surviving the inner join

        6. **Database logging (optional)**
        If `logging=True`:
        • Starts a validation run (`run_id`)
        • Applies `KeyCreator` instances to generate additional identity keys
        • Resolves or creates:
            - `person_id`
            - `participant_id`
        • Logs:
            - normalized cell values
            - participant presence (present / missing)
            - key mismatches
            - validation rule violations

        7. **Cross-sheet rule enforcement**
        • Executes `_apply_cross_rules()` using the merged dataset (`self.single_sheet`)
        • Appends any violations to `self.errors`

        8. **Violation persistence (optional)**
        • Maps `id_key → participant_id`
        • Persists each violation to the database

        Args:
            file (str):
                Workbook identifier, typically `"org|quarter"` or
                `"org|quarter|filename"`. Only the first two segments are used
                to derive `org` and `quarter`.

            workbook_type (str):
                Dataset category (e.g., `"CareerConneCT"`).

            workbook_format (str):
                Layout style defined in `workbook_definitions`
                (e.g., `"simple format"`, `"four sheet format"`).

            dfs_by_sheet (dict[str, pd.DataFrame]):
                Raw DataFrames keyed by sheet name.

            passed_identity_sheet (str):
                Required for multi-sheet formats. Ignored for simple format.

            keycreators (list[tuple], optional):
                List of `(KeyCreator, column_name)` pairs used to generate
                additional identity keys when logging is enabled.

        Returns:
            None

            Results are stored on the instance:
                • `self.normalized_data`  → per-sheet normalized DataFrames
                • `self.single_sheet`     → merged cross-sheet dataset
                • `self.returnable_data`  → normalized-only dataset for downstream use
                • `self.errors`           → all validation errors
                • database tables         → if logging is enabled

        Raises:
            ValueError:
                If the identity sheet is missing.

            KeyError:
                If workbook definitions are incomplete or a sheet schema is missing.

        Notes:
            • The inner join across sheets will drop participants not present in all sheets.
            • Duplicate `id_key` values are removed prior to merging, which may reduce row counts.
            • Column provenance is encoded using the delimiter `_|_|_`.
            • Logging mode performs row-wise operations and may be slow for large datasets.
            • This method mutates internal state and should be called once per workbook.
        """
        self.file = file
        self.column_error_index = {}

        self.org = file.split("|")[0] if isinstance(file, str) else ""
        self.quarter = file.split("|")[1] if isinstance(file, str) else ""

        if self.logging:
            ## create a unique id connected to the information passed in the run table 
            self.run_id =  self.db_logger.start_run(workbook_type, self.org, self.quarter, triggered_by="mwebb", run_description = self.log_description)
            self.db_logger.raw_data_points = dfs_by_sheet
            
            if keycreators:
            
                self.db_logger.keycreators = keycreators

            else: 

                raise ValueError("Keycreators must not be none if logging is enabled.")
    
        # ============================================================
        # 1️⃣ Sheet-by-sheet validation
        # ============================================================
        print(f"{self.org} {workbook_type} - Starting Normalization @ {datetime.now()}")

        for sheet_name, df in dfs_by_sheet.items():

            accepted_responses = self.workbook_definitions[workbook_type][workbook_format][sheet_name]["accepted_responses"]

            norm_df, errs = self._validate_sheet(df, sheet_name, accepted_responses)

            cols_to_check = [c for c in norm_df.columns if c not in ["id_key", f"row_number_{sheet_name}"]]
            norm_df = norm_df.dropna(subset=cols_to_check, how="all")

            self.normalized_data[sheet_name] = norm_df
            if not errs.empty:
                self.errors.append(errs)

        # ============================================================
        # 2️⃣ Identify canonical participants (from identity sheet)
        # ============================================================
        
        if(workbook_format == "simple format"):
            identity_sheet = sheet_name
            id_df = self.normalized_data.get(identity_sheet)
            id_df["id_key"] = (id_df["First Name"].fillna("") + "|" + id_df["Last Name"].fillna(""))
            
            raw_data = dfs_by_sheet.get(identity_sheet)
            if raw_data is None:
                raise KeyError(f"Identity sheet '{identity_sheet}' not found")

            raw_data["id_key"] = (raw_data["First Name"].fillna("") + "|" + raw_data["Last Name"].fillna(""))
        else: 
            identity_sheet = passed_identity_sheet
            id_df = self.normalized_data.get(identity_sheet)
        if id_df is None:
            raise ValueError(f"Identity sheet '{identity_sheet}' not found in workbook.")
        
        # Generate spreadsheet specific keys that can be used to map back to a universal person ID


        print(f"{self.org} {workbook_type} - Recording Mismatches @ {datetime.now()}")

        def record_mismatches(keys, org, quarter, sheet, issue):
            for k in keys:
                self.mismatches.append({
                    "org": org,
                    "period": quarter,
                    "sheet": sheet,
                    "id_key": k,
                    "issue": issue
                })
        # --- Step 1: find all globally duplicated id_keys ---
        all_dup_keys = set()
        for sheet_name, df in self.normalized_data.items():
            if "id_key" in df.columns:
                dup_keys = df.loc[df["id_key"].duplicated(), "id_key"].unique()
                if len(dup_keys) > 0:
                    record_mismatches(dup_keys, self.org, self.quarter, sheet_name, "duplicate_in_sheet")
                    all_dup_keys.update(dup_keys)

        # --- Step 2: drop those keys from every sheet before comparing/merging ---
        cleaned_dfs = []
        for sheet_name, df in self.normalized_data.items():
            if "id_key" in df.columns:
                df = df[~df["id_key"].isin(all_dup_keys)].copy()
            cleaned_dfs.append((sheet_name, df))

        

        # --- Step 3: do matching/missing/extra on the cleaned data ---
        base_name, base_df = cleaned_dfs[0]

        base_df = add_sheet_suffix(
            base_df,
            base_name,
            omitted_columns={"id_key"}
        )

        assert_sheet_provenance(
            base_df,
            omitted_columns={"id_key"}
        )
        merged = base_df.copy()
        _, returnable_data = cleaned_dfs[0]

        for sheet_name, df in cleaned_dfs[1:]:

            if df.columns.duplicated().any():

                dupes = df.columns[df.columns.duplicated()].tolist()

                raise ValueError(
                    f"Duplicate columns detected in '{sheet_name}': {dupes}"
                )
            
            if "id_key" not in df.columns:
                raise ValueError(
                    f"Sheet '{sheet_name}' does not contain id_key."
                )

            base_keys = set(merged["id_key"])
            sheet_keys = set(df["id_key"])

            missing_in_sheet = base_keys - sheet_keys
            extra_in_sheet   = sheet_keys - base_keys

            if missing_in_sheet:
                record_mismatches(missing_in_sheet, self.org, self.quarter, sheet_name, "missing_in_sheet")
            if extra_in_sheet:
                record_mismatches(extra_in_sheet, self.org, self.quarter, sheet_name, "extra_in_sheet")

            dedup_cols = ["First Name", "First Name_normalized", "Middle Name", "Middle Name_normalized", "Last Name", "Last Name_normalized", "source_file"]
            mask = df.columns.isin(dedup_cols)
        
            df = df.loc[:, ~mask].copy()

            returnable_data = returnable_data.merge(df, on="id_key", how="inner")

            df = add_sheet_suffix(
                df,
                sheet_name,
                omitted_columns={"id_key"}
            )

            if df.columns.duplicated().any():

                dupes = df.columns[df.columns.duplicated()].tolist()

                raise ValueError(
                    f"Duplicate columns detected in '{sheet_name}': {dupes}"
                )
            

            assert_sheet_provenance(
                df,
                omitted_columns={"id_key"}
            )

            left_cols = set(merged.columns) - {"id_key"}
            right_cols = set(df.columns) - {"id_key"}

            collisions = left_cols & right_cols

            if collisions:

                formatted = "\n".join(
                    f"    - {c}"
                    for c in sorted(collisions)
                )

                raise ValueError(
                    "Column collision detected before merge.\n\n"
                    "Columns should already contain sheet provenance.\n\n"
                    "Conflicting columns:\n"
                    f"{formatted}"
                )
            
            ### inner merge is catching any stray single participant entries and removing from the dataset that will be processed
            merged = merged.merge(df, on="id_key", how="inner", validate = "one_to_one")
        
        valid_id_keys = set(merged["id_key"])

        id_df_valid = id_df[id_df["id_key"].isin(valid_id_keys)].copy()

        # else: 

        #     # All ids remain valid when mismatch checking is disabled
        #     id_df_valid = id_df.copy()

        #     cleaned_dfs = list(self.normalized_data.items())

        #     if not cleaned_dfs:
        #         merged = pd.DataFrame()
        #     else:
        #         base_name, base_df = cleaned_dfs[0]
        #         merged = base_df.copy()

        #         for sheet_name, df in cleaned_dfs[1:]:

        #             if "id_key" not in df.columns:
        #                 continue

        #             merged = merged.merge(
        #                 df,
        #                 on="id_key",
        #                 how="inner",
        #                 suffixes=("", f"_{sheet_name}")
        #             )

        print(f"{self.org} {workbook_type} - Starting Logging @ {datetime.now()}")

        normalized_combined = merged

        normalized_combined["org"] = self.org
        normalized_combined["period"] = self.quarter


    
        returnable_data = returnable_data.loc[
            :, returnable_data.columns.str.contains("normalized")
        ]

        returnable_data["org"] = self.org
        returnable_data["period"] = self.quarter

        returnable_data = strip_normalized_suffixes(
            returnable_data
        )

        self.single_sheet = normalized_combined

        self.returnable_data = returnable_data

        if self.logging:

            for kc, colname in keycreators:
                self.single_sheet[colname] = self.single_sheet.apply(kc.create_key_from_row, axis=1)

            person_ids = []

            self.db_logger.load_person_maps()

            for _, row in self.single_sheet.iterrows():
                
                pid = self.db_logger.resolve_person(row) ### checks keys, and resolves match or creates new person as needed
                person_ids.append(pid) ## create list of recognized person ids to be added to participant table 

            self.db_logger.flush_new_people_buffer()

            self.single_sheet["person_id"] = person_ids

            # Create or update dataset entries in the DB

            participant_ids = []

            self.db_logger.load_participant_map(workbook_type, self.org)
 
            for _, row in self.single_sheet.iterrows():
                pid = row["person_id"]

                participant_id = self.db_logger.get_or_create_participant(
                    person_id=pid,
                    dataset_name=workbook_type,
                    org=self.org
                )

                participant_ids.append(participant_id)
            
            self.db_logger.flush_new_participants()

            self.single_sheet["participant_id"] = participant_ids
            
            self.db_logger.log_all_normalized_cell_values(
                run_id=self.run_id,
                dataset_name=workbook_type,
                df=self.single_sheet
            )

            ### if this is the first run for a given dataset, mark all participants as present. 
            cur = self.db_logger.conn.execute(
                """
                SELECT COUNT(*) 
                FROM participant 
                WHERE dataset_name=? AND org=?
                """,
                (workbook_type, self.org)
            )
            
            prior_count = cur.fetchone()[0]
            is_first_run = prior_count == 0
            
            row_col = f"row_number_{identity_sheet}_|_|_{identity_sheet}"

            pid_to_row = (
                self.single_sheet
                .set_index("participant_id")[row_col]
                .to_dict()
            )

            seen = set(pid_to_row.keys())

            if is_first_run:
                for pid, row_number in pid_to_row.items():
                    self.db_logger.mark_presence_participant(
                        run_id= self.run_id,
                        participant_id=pid,
                        status="present",
                        row_number=row_number,
                        sheet_name = identity_sheet,
                        quarter = self.quarter
                    )

                self.db_logger.flush_participant_presence()

            else:
                cur = self.db_logger.conn.execute(
                    "SELECT participant_id FROM participant WHERE dataset_name=? AND org=?",
                    (workbook_type, self.org)
                )
                all_ids = [r[0] for r in cur.fetchall()]

                #print(f"There are {len(all_ids)} participant IDs to check presence for.")

                for pid in all_ids:
                    status = "present" if pid in pid_to_row else "missing"
                    row_number = pid_to_row.get(pid)  # None if missing
                    self.db_logger.mark_presence_participant(
                        run_id=self.run_id,
                        participant_id=pid,
                        status=status,
                        row_number=row_number,
                        sheet_name=identity_sheet,
                        quarter=self.quarter
                    )
                    
                self.db_logger.flush_participant_presence()

        if self.mismatches:
            
            filtered = [
                m for m in self.mismatches
                if m.get("id_key") is not None
            ]

            if filtered and self.logging:
                self.db_logger.log_key_mismatches(
                    run_id= self.run_id,
                    mismatches=filtered
                )

        # normalized_combined = merged

        # dedup_cols = ["id_key", "First Name", "Last Name", "source_file"]
        # mask = normalized_combined.columns.duplicated() & normalized_combined.columns.isin(dedup_cols)
        # normalized_combined = normalized_combined.loc[:, ~mask]

        # normalized_combined["org"] = self.org
        # normalized_combined["period"] = self.quarter
        # self.single_sheet = normalized_combined

        # ============================================================
        # 4️⃣ Apply cross-sheet rules
        # ============================================================
        cross_errs = self._apply_cross_rules(workbook_type=workbook_type, workbook_format=workbook_format, file=file)
        if not cross_errs.empty:
            self.errors.append(cross_errs)
        
        if self.logging and self.errors:

            # Combine all sheet-level + cross-sheet errors into one DF
            err_df = pd.concat(self.errors, ignore_index=True)

            # --------------------------------------------------------
            # Attach participant_id to each error row using id_key
            # --------------------------------------------------------
            if "id_key" in err_df.columns:

                # Build lookup: id_key → participant_id
                id_lookup = (
                    self.single_sheet
                    .dropna(subset=["id_key"])
                    .drop_duplicates(subset=["id_key"], keep="first")
                    .set_index("id_key")["participant_id"]
                )

                # Map onto errors
                err_df["participant_id"] = err_df["id_key"].map(id_lookup)

            else:
                # If id_key missing, participant_id cannot be resolved
                err_df["participant_id"] = None

            # --------------------------------------------------------
            # Persist each violation
            # --------------------------------------------------------
            #print(f"There are {len(err_df)} to log in this run.")
            
            for idx, row in err_df.iterrows():

                rule_name = row.get("rule", "")
                col = row.get("column", "")
                normalized = row.get("normalized", "")
                raw_value = row.get("raw_value", "")
                participant_id = row.get("participant_id")
                severity = row.get("severity", "error") # fall back of "error" if a severity can't be found so that users aren't confused but we know we need to troubleshoot.

                column_id = self.db_logger.get_or_create_column(
                    dataset_name = workbook_type, 
                    sheet_name = row.get("sheet"),
                    column_name = col 
                )

                if self.logging: 
                    self.db_logger.log_violation(
                        run_id=self.run_id,
                        rule_id=rule_name,                # optionally: map rule → rule_id
                        participant_id=participant_id,
                        column_id= column_id,               # or your internal column_id
                        normalized=normalized,
                        raw_value=raw_value,
                        severity=severity
                    )

                #print(f"Logging an error for {participant_id} at {col}.")

            self.db_logger.flush_violations()

        if self.logging:

            self.db_logger.complete_run(self.run_id)

                ## remove sheet name delimiter before passing back 

    def _apply_cross_rules(self, workbook_type, workbook_format, file=None, row_offset=1):
        
        """
        Apply all configured cross-sheet and cross-column validation rules.

        This method delegates rule evaluation to `CrossRuleEngine`, operating on the
        fully merged dataset (`self.single_sheet`) produced during
        `validate_workbook`. Rules compare values across columns and sheets to detect
        logical inconsistencies, missing dependencies, or invalid combinations.

        Args:
            workbook_type (str):
                Dataset family (e.g., "CareerConneCT", "Participant Data").

            workbook_format (str):
                Layout format (e.g., "simple format", "four sheet format").

            file (str, optional):
                Workbook identifier. If not provided, `self.file` is used.

            row_offset (int, optional):
                Offset applied when converting DataFrame indices to Excel row numbers.
                Passed through to the rule engine but typically unused here.

        Returns:
            pd.DataFrame:
                Combined DataFrame of all cross-rule violations with columns:
                    ["file", "sheet", "row_number", "column",
                    "rule", "severity", "raw_value", "normalized"]

                Returns an empty DataFrame with the same schema if no violations occur.

        Behavior:
            • Initializes a `CrossRuleEngine` using:
                - `self.single_sheet` (merged dataset across sheets)
                - `self.workbook_definitions` (normalization schema)
                - `self.file` (for error lineage)

            • Iterates through `self.cross_rules`, expected as:
                [(label, ruleset), ...]

            • For each ruleset:
                - Executes all rules via `engine.run_all_rules()`
                - Collects resulting violation DataFrames

            • Concatenates all violations into a single DataFrame.

            • Assigns `"severity" = "Cross"` to all returned violations.

            • Sets `self._cross_checked = True`.

        Notes:
            • Rules operate on the merged dataset (`self.single_sheet`), not on
            individual per-sheet DataFrames.
            • Column names may include sheet provenance suffixes using the delimiter
            `_|_|_` (e.g., `"First Name_|_|_Training"`).
            • Missing or empty rule sets are skipped silently.
            • Row numbering in outputs depends on upstream normalization and may
            reflect sheet-specific row number columns.
            • Downstream processes (e.g., logging) are responsible for attaching
            `participant_id` to violations.
        """

        # 1️⃣ Initialize the engine
        engine = CrossRuleEngine(
            workbook_type = workbook_type,
            workbook_format = workbook_format,
            normalized_single_sheet= self.single_sheet,
            normalization_schema=self.workbook_definitions,
            file = self.file
        )

        # 2️⃣ Run each rule category through the engine
        all_violations = []

        rule_sets = self.cross_rules

        for label, ruleset in rule_sets:
            if not ruleset:
                continue

            violations = engine.run_all_rules(ruleset)

            if violations is not None and not violations.empty:
                violations["severity"] = "Cross" # label violation as Cross
                all_violations.append(violations)

        # 3️⃣ Combine all violation DataFrames
        if all_violations:
            combined = pd.concat(all_violations, ignore_index=True)
        
        else:
            combined = pd.DataFrame(
                columns=["file", "sheet", "row_number", "column", "rule", "severity", "raw_value", "normalized"]
            )

        self._cross_checked = True
        return combined

    def get_all_errors(self):
        """
        Return a single DataFrame containing all accumulated validation errors.

        This method aggregates:
        - Sheet-level column-type validation errors generated during
          `_validate_sheet()`
        - Any cross-sheet rule violations produced by `_apply_cross_rules()`

        Errors are returned in a consistent, flat structure suitable for:
        - Export to Excel/CSV
        - Display in UI dashboards
        - Insertion into logging or auditing pipelines
        - Downstream analytics (e.g., error frequency reports)

        Returns:
            pandas.DataFrame:
                A DataFrame with the standardized columns:
                ["file", "sheet", "row_number", "column", "rule", "severity",
                 "raw_value", "normalized"]

                If no errors have been recorded, an empty DataFrame with
                the correct schema is returned.

        Notes:
            • This does *not* modify internal state.
            • Errors remain stored in `self.errors`.
            • Calling this multiple times is inexpensive and safe.
        """
        if not self.errors:
            return pd.DataFrame(columns=["file","sheet","row_number","column","rule", "severity", "raw_value","normalized"])
        return pd.concat(self.errors, ignore_index=True)
